link:#pre-core-values-considerations[[.underline]#Pre-Core Values
Considerations#]

____
link:#the-lack-of-a-shared-understanding-around-supporting-a-people-targeted-by-genocide[[.underline]#The
Lack of a Shared Understanding Around Supporting a People Targeted by
Genocide#]

link:#the-lack-of-a-shared-understanding-of-what-type-of-aid-ypc-is-best-suited-to-deliver[[.underline]#The
Lack of a Shared Understanding of What Type of Aid YPC is Best Suited to
Deliver#]

link:#nuances-between-help-and-mutual-aid[[.underline]#Nuances Between
“Help” and “Mutual Aid”#]

link:#next-steps[[.underline]#Next Steps:#]

link:#declaration-of-genocide[[.underline]#1. Declaration of genocide?#]

link:#scope-of-aid[[.underline]#2. Scope of aid#]

link:#defining-aid-vs-help[[.underline]#3. Defining aid vs help#]
____

link:#core-values-and-principles[[.underline]#Core Values and
Principles#]

____
link:#pyramid-of-values[[.underline]#Pyramid of Values#]

link:#safety-and-efficiencyeffectiveness-knobslevers[[.underline]#Safety
and Efficiency/Effectiveness: Knobs/Levers#]

link:#next-steps-1[[.underline]#Next Steps:#]

link:#define-core-values[[.underline]#1. Define core values#]

link:#define-principles[[.underline]#2. Define principles#]


== Pre-Core Values Considerations

Clarity in these areas will help develop the core values.

=== The Lack of a Shared Understanding Around Supporting a People Targeted by Genocide

In original onboarding documents, it wasn’t mentioned that the Israeli
government is committing genocide, backed by US dollars, and US
political support. That may seem political and unnecessary when the
stated goal is just to “help people”, but if we aren’t naming the reason
_why_ we are anxious and trying to move rapidly to help Gazans in the
first place, we will miss some very critical points in our attempts to
deliver aid.

Focusing on helping the ‘marginalized’ or ‘oppressed’ without
acknowledging and challenging the systems, and actors who are doing the
marginalization or oppression actually maintains and supports harm to
keep happening towards the very people we wish to help.

How does this specifically affect this project? I believe it’s
imperative that we:

* Have a shared understanding that we are aiming to support people being
targeted for a genocide, and thus acknowledge that _there are bad actors
at play that we have to be aware of_ and obfuscate.
* Acknowledge that _the seeking of aid & support_ in of itself has been
used in multiple ways to attack Gazans, and therefore we *_have to_*
ensure that the tool we develop in trying to support them can not be
used to harm them.
* We acknowledge that the very nature of trying to break barriers in
providing aid, may be counter to the goals of the current US government,
and there may be attempts to try to stop this project from law
enforcement, etc. (there is precedence for this)
* Understand that there _will_ be ‘bad actors’ that _will_ attempt to
infiltrate this collective, and/or people with the intention to directly
troll, taunt, or harass the people of Gaza who may want to sign up as
volunteers.
* We acknowledge that although our best intentions are good, our efforts
could unintentionally cause more harm, if we jump into a situation
without adequate knowledge.
* Because of these stated things, proper training, vetting of
volunteers, _and privacy protocols_ is essential to anyone who would:
** Be able to alter/share information from the webpage
** Have access to any identifiable information from Gazan’s asking for
help
** Be speaking to or supporting Gazans directly

=== The Lack of a Shared Understanding of What Type of Aid YPC is Best Suited to Deliver

There are a lot of potential harms that could be created by connected
masses of untrained, uninformed volunteers to folks experiencing a
direct genocide, _is the possibility that the aid that is delivered is
in itself, harmful and unhelpful._ A few questions we need to sit with:

[arabic]
. What biases or assumptions might we have internalized about the
inherent value “aid givers”, or volunteers could provide?
. Do we have an informed, clear understanding of what requests for aid
are coming from _[.mark]#folks in Palestine, by Palestinians?#_
. Can we bring on board people with experience in giving aid to people
experiencing war, in order to train volunteers?

What volunteers we prioritize to onboard (professions, skill sets, etc)
and what training those volunteers need should be determined by the
direct vocalized needs of folks in Gaza.

*Potential Harms as YPC as a Peer to Peer Connector*

If we using YPC to link Palestinians directly to a mass of volunteers
who want to connect, we could be connecting folks in the midsts of one
of the most intense crises’ ever to people who have no background in:

* Crisis intervention
* Trauma-informed care
* Decolonized mental health practices
* Palestinian language and culture
* Anti-oppressive practices

Although there is value in connecting folks across culture, building
connections, relationships, and connecting humans to humans. The harms
can be life-threatening and can include:

* Any harms that would ordinarily be considered malpractice (without any
protections of licensing bodies)
* Exposing those seeking help to racism, religious proselytizing,
classism, and more from folks who are “well-intentioned”
* Violations of privacy, of intentionally or unintentionally exposing
details of private conversations that would put Gazans at psychological,
physical or emotional risk
* Exploitation (of personal shared stories) and/or abuse within the chat

https://docs.google.com/document/d/1QHX9B58asAs4IaJIrrQ73SsmnwWtNuKa3EXQqzMmD1U/edit?usp=sharing[[.underline]#This
is an editable list of possible uses of YPC for delivering aid#]

=== Nuances Between “Help” and “Mutual Aid”

T[.mark]##he word "help" in itself needs to be cleared up. It's vague,
focuses more on the intentions of the "giver" instead of the impact of
the actions, further perpetuates 'top down charity' ideas, and is
distinctly different from mutual aid. As much as possible, let's clarify
what we are aiming to do, provide, etc.##

[.mark]#In an article entitled
https://briarpatchmagazine.com/articles/view/the-co-option-of-mutual-aid[[.underline]#Co-opting
Mutual Aid#] author
https://briarpatchmagazine.com/contributors/view/de-loggans-regan[Regan
de Loggans] made two different points this collective may consider:#

* [.mark]#Mutual aid defies the hierarchies and white saviorism inherent
to charity, instead asking us to share our skills and resources in order
to decentralize community care, and help one another break free from
capitalism and colonial authority.#
* [.mark]#We are being quite literal when we say that mutual aid, when
practiced by people of color, has led to community members being
targeted, incarcerated, and murdered by the government.#

[.mark]#Specifically to the last point, a mutual aid project that
supports folks being targeted in genocide may lead to several
implications for the organizers and volunteers:#

* [.mark]#Being listed or identified as supporting and abetting “enemies
of the state”#
* [.mark]#Secondary and/or vicarious trauma#

=== Next Steps: 

==== Declaration of genocide?

==== Scope of aid

==== Defining aid vs help
